### ISSUE TITLE
Installing LIQA

### ISSUE THREAD

**Issue by dvirdi01** [WGLab/LIQA#37]
I installed liqa through pip but when I run liqa in my terminal it says 
Traceback (most recent call last):
  File "/storage/..../..../..../.../..../bin/liqa", line 5, in <module>
    from liqa_src.liqa import main
  File "/storage/..../...../...../..../..../lib/python3.12/site-packages/liqa_src/liqa.py", line 3, in <module>
    from liqa_src import my_functions as my
  File "/storage/..../..../..../.../..../.../python3.12/site-packages/liqa_src/my_functions.py", line 59, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

**Comment by sparthib** [comment]
Hi @dvirdi01, I ran into the same error. Were you able to solve this issue? Thanks! 

I'm pasting my environment information here for more context: @huyustats, if you have any insights please let me know, thanks! 

```
name: LIQA
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.40=hf600244_0
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.22.1=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - curl=8.4.0=hca28451_0
  - expat=2.5.0=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=13.2.0=h338b0a0_3
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=13.2.0=h76e1118_3
  - graphite2=1.3.13=h58526e2_1001
  - gxx_impl_linux-64=13.2.0=h338b0a0_3
  - harfbuzz=8.3.0=h3d44ed6_0
  - icu=73.2=h59595ed_0
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=20_linux64_openblas
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=13.2.0=ha9c7c90_103
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libglib=2.78.1=h783c2da_1
  - libgomp=13.2.0=h807b86a_3
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=20_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libsanitizer=13.2.0=h7e041cc_3
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=13.2.0=ha9c7c90_103
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - make=4.3=hd18ef5c_1
  - ncurses=6.4=h59595ed_2
  - openssl=3.2.0=hd590300_1
  - pango=1.50.14=ha41ecd1_2
  - pcre2=10.42=hcad00b1_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.12.0=hab00c5b_0_cpython
  - r-base=4.3.2=hb8ee39d_1
  - readline=8.2=h8228510_1
  - sed=4.8=he412f7d_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - sysroot_linux-64=2.12=he073ed8_16
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h0c5db8f_5
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - astor==0.8.1
      - autograd==1.6.2
      - autograd-gamma==0.5.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.45.1
      - formulaic==0.6.6
      - future==0.18.3
      - interface-meta==1.3.0
      - kiwisolver==1.4.5
      - lifelines==0.27.8
      - liqa==1.3.4
      - matplotlib==3.8.2
      - numpy==1.26.2
      - packaging==23.2
      - pandas==2.1.3
      - pillow==10.1.0
      - pyparsing==3.1.1
      - pysam==0.22.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - scipy==1.11.4
      - six==1.16.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - wrapt==1.16.0
prefix: /users/sparthib/.conda/envs/LIQA
```

**Comment by agouru55** [comment]
Yes, the above comment has the correct packages. Perhaps try to install with git clone instead (as it will have the most up to date version) and see if you still run into issues.
More info is on the Install link: https://github.com/WGLab/LIQA/blob/master/doc/Install.md
