### ISSUE TITLE
ValueError: invalid coordinates: start (10589) > stop (9435)

### ISSUE THREAD

**Issue by hmutpw** [WGLab/LIQA#6]
The refgene file has an error with chromosome start and end, for example:
Vmn2r122        JH584292.1      +       10589   9435    ENSMUST00000178970.7,ENSMUST00000096791.11,ENSMUST00000099422.4,ENSMUST00000179115.1,ENSMUST00000071277.13,

**Comment by huyustats** [comment]
Hi,

I think this was caused by error in the GTF file. LIQA will eliminate this gene when doing analysis.

**Comment by Y0NEKO** [comment]
> Hi,
> 
> I think this was caused by error in the GTF file. LIQA will eliminate this gene when doing analysis.

Hi, I had a same error when quantifying
```
Traceback (most recent call last):
  File "/lustre/home/acct-medsjf/medsjf-user1/.local/lib/python3.9/site-packages/liqa_src/quantify.py", line 153, in <module>
    for read in bamFilePysam.fetch(geneChr, geneStart, geneEnd):
  File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 688, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid coordinates: start (100003847) > stop (99995921)
```
What could be the reason?

**Comment by rsalz** [comment]
I am having the same issue with '-task quantify'. I am using a matching genome/annotation file, and i even re-aligned to be completely sure the error wasn't from my side. I get:
```
Traceback (most recent call last):
  File "/home/renees/anaconda3/envs/swanvis/lib/python3.7/site-packages/liqa_src/quantify.py", line 153, in <module>
    for read in bamFilePysam.fetch(geneChr, geneStart, geneEnd):
  File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 688, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid coordinates: start (10004092) > stop (9997331)
```

**Comment by huyustats** [comment]
Thank you for your comments! This bug has been fixed.
